server_extensions_extra/res/batm-extensions.xml
server_extensions_extra/src/com/generalbytes/batm/server/extensions/extra/bitcoin/BitcoinExtension.java
server_extensions_extra/src/com/generalbytes/batm/server/extensions/extra/bitcoin/wallets/bitcore/BitcoreWallet.java
server_extensions_extra/src/com/generalbytes/batm/server/extensions/extra/bitcoin/wallets/bitcore/IBitcoreProxyAPI.java

Here's the IWallet implementation I was working on.
It communicates with an instance of BitCore wallet service, but since there is no Java client for it (and it's fairly complicated), I use a Node.js proxy. That project is here: https://github.com/chrisrico/babywasp
Anybody can install this Node program on a server and use it to generate a wallet (1-of-1 up to 4-of-6 multisig). The wallet file is then encrypted with a randomly generated private key, which is used as an API key by the BATM server. The nice thing about this is that the proxy can be pointed at any wallet service, even Bitpay's (in fact it defaults to theirs). When the wallet is created, it also displays the key converted to a 12 word mnemonic. Using this mnemonic, the encryption key on the wallet can be changed, in effect …

Add IWallet implementation for BWS (via proxy)

---

server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/bitcore/BitcoreAddressValidator.java

Bitcore made a Wallet Update to change the Wallet Letters:
1 --> 2
3 --> s
SLIP44=160
COIN_P2PKH_VERSION=3
COIN_P2SH_VERSION=125
https://github.com/LIMXTEC/BitCore/blob/0.15/src/chainparams.cpp#L143

Change BTX Wallet Vars

---

server_extensions_extra/build.gradle
server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/anon/ANONExtension.java
server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/bitcoinprivate/BitcoinPrivateExtension.java
server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/cloakcoin/CloakcoinExtension.java
server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/dash/DashExtension.java
server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/dash/sources/coinmarketcap/CmcTickerData.java
server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/dash/sources/coinmarketcap/CmcTickerResponse.java
server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/dash/sources/coinmarketcap/CoinmarketcapRateSource.java
server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/dash/sources/coinmarketcap/ICoinmarketcapAPI.java
server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/electra/ElectraExtension.java
server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/linda/LindaExtension.java
server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/lisk/LiskExtension.java
server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/lisk/sources/binance/BinanceRateSource.java
server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/pac/PacExtension.java
server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/syscoin/SyscoinExtension.java
server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/zcoin/ZcoinExtension.java
server_extensions_extra/src/main/resources/batm-extensions.xml
server_extensions_extra/src/test/java/com/generalbytes/batm/server/extensions/extra/dash/sources/coinmarketcap/CoinmarketcapAPITest.java
server_extensions_extra/src/test/java/com/generalbytes/batm/server/extensions/extra/dash/sources/coinmarketcap/CoinmarketcapRateSourceTest.java
server_extensions_extra/src/test/java/com/generalbytes/batm/server/extensions/extra/dash/sources/coinmarketcap/TestCoinmarketcapAPI.java

- api key is needed now, see https://pro.coinmarketcap.com/migrate/
- Binance rate source used coinmarketcap too so it needs the key too now

BATM-780 migrate to the new coinmarket pro-api

---

dependencyChecksums.txt
dependencySubstitutions.txt

1.1 has different checksums on central and jcenter

BPUB-793 update guava's dependency j2objc-annotations to 1.3

---

server_extensions_extra/src/main/resources/batm-extensions.xml

"hidden for security reasons" was not displayed when a value was configured

BPUB-613 coinbase pro ratesource param description

---

server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/lightningbitcoin/LightningBitcoinPaymentSupport.java

this bug randomly stopped other PaymentSupports from being loaded

BPUB-649 fix LightningBitcoinPaymentSupport init method

---

server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/common/AbstractRPCPaymentSupport.java
server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/dash/DashAddressValidator.java
server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/dash/DashDefinition.java
server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/dash/DashExtension.java
server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/dash/DashPaperWallet.java
server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/dash/DashPaymentSupport.java
server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/dash/DashWalletGenerator.java
server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/dash/test/PO.java
server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/dash/test/PRS.java
server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/dash/wallets/DashRPCClient.java
server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/dash/wallets/DashTransaction.java
server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/dash/wallets/MapWrapper.java
server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/dash/wallets/dashd/DashRPCWallet.java
server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/dash/wallets/dashd/DashUniqueAddressRPCWallet.java
server_extensions_extra/src/main/resources/batm-extensions.xml

* Support InstantSend via dashd RPC
* Support X (P2PKH) and 7 (P2SH) address prefixes
**Explanation of Changes:**
The BitcoinCash extension was used as a template while pulling existing code that was present as part of the Dash extension.
Since Dash has extra fields in the `gettransaction` and `getrawtransaction` commands that are not exposed by the Bitcoin-JSON-RPC-Client library, these classes and interfaces were added:  `DashTransaction`, `DashTransactionWrapper`, `MapWrapper` (duplicated from BitcoinJsonRPC but cause it is a private class) and `DashRPCClient`.
getPaymentReceipt was overriden from AbstractRPCPaymentSupport to add `CONFIDENCE_SURE` if the transaction is locked by the InstantSend mechanism.  I don't like the way this was done, but it seems like some changes to …

Update DASH extension

---

server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/bitcoin/exchanges/bittrex/BittrexExchange.java

the code was expecting "success" string as a result but the exchange was returning an uuid.
Exception should be thrown and catched in case of a failure.

BPUB-1176 fix bittrex withdrawal

---

dependencyChecksums.txt
server_extensions_extra/build.gradle
server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/bitcoin/BitcoinExtension.java
server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/bitcoin/exchanges/XChangeExchange.java
server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/bitcoin/exchanges/binance/BinanceComExchange.java
server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/bitcoin/exchanges/binance/BinanceExchange.java
server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/bitcoin/exchanges/binance/BinanceJerseyExchange.java
server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/bitcoin/exchanges/binance/BinanceUsExchange.java
server_extensions_extra/src/main/resources/batm-extensions.xml
server_extensions_extra/src/test/java/com/generalbytes/batm/server/extensions/extra/bitcoin/exchanges/binance/BinanceExchangeTest.java
server_extensions_extra/src/test/resources/logback-test.xml

Support for Binance.com (no fiat), Binance US (USD) and Binance Jersey (EUR, GBP).
We have another feature requests to use stablecoins as fiat which would be useful for binance.com users.

BPUB-1164 binance exchange

---

server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/bitcoin/exchanges/XChangeExchange.java
server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/bitcoin/exchanges/binance/BinanceExchange.java

when rate source was cached there were still a few unnecessary HTTP calls from the exchange constructor.
Now it is initialized only when needed.

BPUB-1211 limit unnecessary HTTP calls from XChangeExchange

---

server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/bitcoin/wallets/bitgo/v2/BitgoWallet.java

sendCoins has to return null if it fails, it returned "ERROR" string instead

BATM-1220 fix BitGo sendCoins failed call was reported as successful

---

server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/bitcoin/exchanges/bitfinex/BitfinexExchange.java

BCH pairs  missing in the remote init but present if calling only local init (from a json config file)

[Bitfinex] fix BCH - do not call remote init

---

server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/bitcoin/exchanges/hitbtc/HitbtcExchange.java

"Main" wallet is no longer returned by the xchange library and we only logged it

Fix nullpointer in hitbtc

---

server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/dogecoin/wallets/blockio/BlockIOWalletWithClientSideSigning.java

"Invalid value for parameter AMOUNTS provided" was returned by the host
if the amount had more than 8 decimal places

GB-232 blockio - fixed amount rounding

---

server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/common/PollingPaymentSupport.java

Completed requests are kept in the memory for some time before being removed so a POS can ask if they're paid.

BATM-1333 fix PollingPaymentSupport to support POS payments too

---

server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/bitcoin/exchanges/bitpandapro/BitpandaProExchange.java
server_extensions_extra/src/test/java/com/generalbytes/batm/server/extensions/extra/bitcoin/exchanges/bitpandapro/BitpandaProExchangeTest.java

Limit orders were created using the price from `calculateBuyPrice` and
`calculateSellPrice` respectively. But these methods do not yield a
limit order price, but the full price to buy the given amount of
cryptos.
Add `amount_precision` for each market and round crypto amounts to not
exceed the allowed precisions.

GB-1464 Fix Bitpanda Pro amount precision and price calculation

---

server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/bitcoin/sources/coingecko/CoinGeckoRateSource.java
server_extensions_extra/src/main/resources/batm-extensions.xml

This pull request adds missed ILCoin crypto currency to CoinGeckoRateSource

Add ILCoin to coingecko rate source

---

server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/ethereum/InfuraWallet.java

- mark transaction as failed when sending timeouts
- estimate gas properly - hardcoded value was used before that wasn't enough for sending to contract addresses

BPUB-1394 fix InfuraWallet

---

server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/util/net/HexStringCertTrustManager.java

Certificate pinning in `HexStringCertTrustManager` could easily be circumvented, this PR fixes this.
The method argument `chain` in `X509TrustManager.checkClientTrusted(X509Certificate[] chain, String authType)` receives a list of certificates which it received from a TLS server during the TLS handshake in the `Certificate` message directly after the `ServerHello` message. 
This list of certificates contains at least the servers own certificate but may also contain an arbitrary number of addidtional certificates. (This normally might be intermediate certificates provided by the server to enable the TLS client to build a valid trust chain from the server's own certificate until a known trusted root-certificate.)
The key points are: 
- certificates are public knowledge (anybody can retrieve …

Security: fix certificate pinning in HexStringCertTrustManager

---

server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/bitcoin/exchanges/bitpandapro/BitpandaProExchange.java
server_extensions_extra/src/test/java/com/generalbytes/batm/server/extensions/extra/bitcoin/exchanges/bitpandapro/BitpandaProExchangeTest.java
server_extensions_extra/src/test/java/com/generalbytes/batm/server/extensions/extra/bitcoin/exchanges/bitpandapro/BitpandaProRateSourceTest.java

Market was opened today (2020-11-12) and trading will start on 2020-11-19 .

[BitpandaPro] Support BTC/GBP

---

server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/bitcoin/exchanges/XChangeExchange.java
server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/bitcoin/exchanges/binance/BinanceExchange.java

The buyer's wallet received the amount we specify in the api call subtracted by a withdraw fee.
After this change we will ask to withdraw (send) the "amount" + withdraw fee to get just the "amount" to the destination address.

BPUB-1455 binance withdraw fee

---

server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/watchlists/eu/ParsedSanctions.java

wholename match against lastname result with score only 50 to avoid false positives when wholename is just firstname/lastname (John)

BPUB-1433 eu sanction list fix

---

server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/bitcoin/BitcoinExtension.java
server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/bitcoin/wallets/bitgo/v2/BitgoWallet.java
server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/bitcoin/wallets/bitgo/v2/BitgoWalletWithUniqueAddresses.java
server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/bitcoin/wallets/bitgo/v2/dto/BitGoCoinRequest.java
server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/bitcoin/wallets/bitgo/v2/dto/BitGoSendManyRequest.java
server_extensions_extra/src/main/resources/batm-extensions.xml
server_extensions_extra/src/test/java/com/generalbytes/batm/server/extensions/extra/bitcoin/wallets/bitgo/v2/BitgoWalletTest.java

Adds the ability to use the `numBlocks` API parameter, that is used to calculate mining fees, as an optional parameter to allow operators to manage their fee expenses when the network is congested.
By default BitGo uses a 2-block target to calculate the transaction's mining fee, which may result in expensive fees for some transactions. Using a higher block target (i.e. 20) would result in cheaper fees, but also longer confirmation times.

BPUB-1365 BitGo adds numblocks parameter

---

gradle.properties
server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/bitcoin/wallets/bitgo/v2/BitgoWallet.java

from documentation
> Balance Strings
> On most digital currencies, the wallet, transaction and address objects all contain a balance property.
> 
> In BitGo Platform V2, we have introduced a String suffix for all balances, as certain digital currencies (such as Ethereum) feature balance ranges which exceed those that can be stored as a typical number in JavaScript.
> 
> While the balance property will continue to be a number, it will not be available on all currencies across the V2 platform. We recommend using balanceString instead of balance for this reason, and balanceString will be available as a property over all digital currencies on V2. This applies to all number properties.

BPUB-1560 bitgo balance - prefer balanceString from response

---

README.md
verification_site/README.md
verification_site/src/main/java/com/generalbytes/verification/service/ApplicantService.java
verification_site/src/main/resources/application-local.properties
verification_site/src/main/resources/application.properties
verification_site/src/main/resources/static/onfido.html
verification_site/src/main/resources/static/style.css

- better documentation specially for HTTPS certificate
- changing default config to be able to run application in default (https config should not be required, it can be behind reverse proxy which is very common usecase these days)
- upgrading to latest onfido release + fixing css style issue

BATM-1844 onfido documentation  + minor fixes

---

server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/bitcoin/wallets/bitgo/v2/BitgoWallet.java
server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/bitcoin/wallets/bitgo/v2/dto/BitGoCoinRequest.java
server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/bitcoin/wallets/bitgo/v2/dto/BitGoSendManyRequest.java
server_extensions_extra/src/test/java/com/generalbytes/batm/server/extensions/extra/bitcoin/wallets/bitgo/v2/BitgoAPITest.java

Allows to pass a `String` object as the comment parameter for the API's request by leveraging the existing description parameter in `sendMany` and `sendCoins` methods. Use cases include transaction ID recording for audit, etc.

Enables BitGoWallet's sendMany and sendCoins to use description

---

server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/bitcoin/exchanges/bitpandapro/BitpandaProExchange.java
server_extensions_extra/src/test/java/com/generalbytes/batm/server/extensions/extra/bitcoin/exchanges/bitpandapro/BitpandaProExchangeTest.java

- Left out new markets from BitpandaProRateSourceTest, because they are not a part of our staging environment
currencies:
- USDT
- ADA
- LTC
- BCH
- TRX
markets:
- LTC_EUR
- USDT_EUR
- ADA_EUR
- BCH_EUR
- TRX_EUR

[BitpandaPro] Updated market and currency list for BitpandaProExchange

---

gradle.properties
server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/bitcoin/exchanges/bittrex/BittrexAccountServiceCustom.java
server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/bitcoin/exchanges/bittrex/BittrexAuthenticatedCustom.java
server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/bitcoin/exchanges/bittrex/BittrexExchange.java
server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/bitcoin/exchanges/bittrex/BittrexExchangeCustom.java
server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/bitcoin/exchanges/bittrex/dto/BittrexNewWithdrawal.java
server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/bitcoin/exchanges/bittrex/dto/BittrexWithdrawal.java

Missing implementation of BittrexAccountService#withdrawFunds in org.knowm.xchange:xchange-bitfinex library, created PR: https://github.com/knowm/XChange/pull/4159

BATM-2323 Temporary fix for unimplemented BittrexAccountService#withdrawFunds

---

server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/lightningbitcoin/wallets/eclair/EclairWallet.java
server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/lightningbitcoin/wallets/lnd/LndWallet.java

preimage should be stored in transaction record instead of payment hash (i.e. hash of the preimage) because it could be used to prove an invoice was paid
Any non null string returned is considered as successful sending

BATM-2361 LN wallets - return preimage instead of payment hash

---

dependencyChecksums.txt
dependencySubstitutions.txt
gradle.properties
server_extensions_extra/build.gradle

https://github.com/pvyhnal-generalbytes/libdohj/commit/a324670d5d55fb4e2d4dd855cf96e632efd1d7f5 should be forked to GB repo OR if upstream merges my PR, we can switch back to the upstream fork https://github.com/dogecoin/libdohj/pull/63
This is version  1.0.49.1 for production,
it also needs to be merged in master

BPUB-1772 update libdohj to fix ltc and doge transactions on block.io

---

gradle.properties
server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/bitcoin/BitcoinExtension.java

BNB needs to be in a list of supported currencies of any extension, otherwise the Tag Feature is not set (tag not required on terminal)

BATM-3007 BNB tag feature fix

---

server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/ethereum/InfuraWallet.java

- The current implemetation of the Infura.io wallet tries to wait for a `TransactionReceipt` to get the txId of the created transaction. 
- This means it needs to wait until the transactions is mined into a block (which could take from seconds to hours).
- The HTTP connection to infura does not stay open this long
- Also, the txId is already available as soon as the signed transaction is created (its the hash), so no need to wait for a block just to get the txId
- rewrites the `sendCoins()` method to use `RawTransactionManager` to manually create a transaction
- it then immediately knows the txId and can return it immediately after broadcasting

Make infura wallet immediately return the txid

---

gradle.properties
server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/bitcoin/exchanges/bitfinex/BitfinexExchange.java
server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/watchlists/ca/ParsedSanctions.java
server_extensions_extra/src/test/java/com/generalbytes/batm/server/extensions/extra/watchlists/ca/ParsedSanctionsTest.java

BATM-5894 Added support for EUR, GBP and JPY at BitfinexExchange
BATM-5900 Fixed false positives when scanning CA sanction list and matching using aliases

BATM-5894 and BATM-5900 bug fixes

---

server_extensions_api/src/main/java/com/generalbytes/batm/server/extensions/IDepositDetails.java
server_extensions_api/src/main/java/com/generalbytes/batm/server/extensions/IDepositPreparation.java
server_extensions_api/src/main/java/com/generalbytes/batm/server/extensions/IDepositRequest.java
server_extensions_api/src/main/java/com/generalbytes/batm/server/extensions/ITransactionListener.java

BATM-6033 Improve IDepositX API to return similar data as ITransactionX interfaces

---

server_extensions_api/src/main/java/com/generalbytes/batm/server/extensions/aml/verification/IIdentityVerificationProvider.java
server_extensions_api/src/main/java/com/generalbytes/batm/server/extensions/aml/verification/OverrideVerificationWebUrlRequest.java
server_extensions_api/src/main/java/com/generalbytes/batm/server/extensions/aml/verification/OverrideVerificationWebUrlResponse.java

* CF-874: Add a method to override verification web URL in identity verification providers
* CF-874: Lombok and javadoc update
(cherry picked from commit 14aadf49a24618dec563fbc6ba40f9e1a351d469)

CF-874: Add a method to override verification web URL (#1040) (#1051)

---

README.md
batm_ssh_tunnel/README.md

In documentation we mention Java 8. We need to mention Java 11 as a minimum version

BATM-7666 - Java 11 must be mentioned as a minimum for compilation
