GENERALBYTESCOM/batm_public

server_extensions_api/build.xml, server_extensions_extra/build.xml, server_extensions_test/build.xml
Gives better output for debugging while is compiling.
=> Better debugging while compiling with ant

server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/sumcoin/SumcoinAddressValidator.java
Line 29 "|| address.startsWith("sum1"))
=> Added bech32 addresses starting "sum1"

server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/futurocoin/FuturocoinExtension.java, server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/futurocoin/sources/coindeal/CoindealRateSource.java, server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/futurocoin/sources/coindeal/ICoindealApi.java, server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/futurocoin/sources/coindeal/dto/CoindealResponse.java, server_extensions_extra/src/main/resources/batm-extensions.xml
FTO rate source from https://coindeal.com/ exchange
=> FTO rate source from coindeal exchange

server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/bitcoin/sources/mrcoin/MrCoinRateSource.java, server_extensions_extra/src/main/resources/batm-extensions.xml
and use api.mrcoin.eu instead of www.mrcoin.eu to avoid an extra redirect
=> Add BCH and LTC support to MrCoin

server_extensions_api/src/main/java/com/generalbytes/batm/server/extensions/Currencies.java
Please merge together with Bitbucket:  BPUB-857-support-for-bhd-currency
=> BPUB-857 BHD support added

server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/ethereum/EthereumExtension.java, server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/ethereum/InfuraWallet.java, server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/ethereum/erc20/ERC20Wallet.java, server_extensions_extra/src/main/resources/batm-extensions.xml
Infura wallet now requires authentication using dashboard generated PROJECT_ID
=> Infura wallet project

currencies/src/main/java/com/generalbytes/batm/common/currencies/CryptoCurrency.java
Spelling presentation correction
=> SumCoin --> Sumcoin

server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/dash/DashAddressValidator.java, server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/litecoin/LitecoinAddressValidator.java
Allowed Email Or SMS purchases for LTC and DASH.
=> BATM-885: LTC Email Or SMS Purchases don't work

currencies/build.gradle, server_extensions_api/build.gradle, server_extensions_api/src/main/java/com/generalbytes/batm/server/extensions/DummyExchangeAndWalletAndSource.java, server_extensions_api/src/main/java/com/generalbytes/batm/server/extensions/IAmount.java, server_extensions_api/src/main/java/com/generalbytes/batm/server/extensions/IEventRecord.java, server_extensions_api/src/main/java/com/generalbytes/batm/server/extensions/IExtensionContext.java, server_extensions_api/src/main/java/com/generalbytes/batm/server/extensions/ITerminal.java, server_extensions_api/src/main/java/com/generalbytes/batm/server/extensions/ITerminalCashCollectionRecord.java
=> Localcoin reporting interfaces

currencies/src/main/java/com/generalbytes/batm/common/currencies/FiatCurrency.java
Add Fiat VES - Bolívares soberanos
=> Add Fiat VES

dependencyChecksums.txt, dependencySubstitutions.txt, server_extensions_extra/build.gradle
this fixes bitfinex rate source
=> BATM-907 update xchange-bitfinex

server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/bitcoin/BitcoinExtension.java, server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/bitcoin/wallets/bitcoind/BATMBitcoindRPCWallet.java, server_extensions_extra/src/main/resources/batm-extensions.xml
support removed in bitcoin core 0.18
deprecatedrpc=accounts not needed anymore
=> BPUB-962 remove accountname bitcoind parameter

server_extensions_extra/src/main/resources/batm-extensions.xml
only available to BitGo Enterprise customers
=> BPUB-662 bitgo wallet ETH support

currencies/src/main/java/com/generalbytes/batm/common/currencies/CryptoCurrency.java
Please merge my changes with master baranch
=> Update CryptoCurrency.java - add XORI

server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/bitcoincash/BitcoinCashPaymentSupport.java, server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/common/AbstractRPCPaymentSupport.java, server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/common/RPCBlockchainWatcher.java, server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/nuls/NulsExtension.java, server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/sumcoin/SumcoinPaymentSupport.java, server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/util/net/HexStringCertTrustManager.java
=> improve extensions logging

server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/bitcoincash/BitcoinCashPaymentSupport.java, server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/common/RPCClient.java
-deprecatedrpc=estimatefee not needed anymore
=> BPUB-1080 support bitcoin-abc (BCH) 0.20

server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/bitcoincash/BitcoinCashExtension.java, server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/bitcoincash/sources/telr/ITelrRateSource.java, server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/bitcoincash/sources/telr/TelrRateSource.java, server_extensions_extra/src/main/resources/batm-extensions.xml
Greetings GB Team,
This is our first pull request, so please do let us know if there are any errors and/or omissions that may be present either in the code itself or with the procedures for adding a new BATM Rate Source. 
This new rate source will be used by 2 new wallets that we are currently testing internally, to be released in the next few weeks.
Cheers!
=> Added Telr.io rate source to Bitcoin Cash extension folder.

server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/bitcoincash/BitcoinCashExtension.java, server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/bitcoincash/sources/telr/ITelrRateSource.java, server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/bitcoincash/sources/telr/TelrRateSource.java, server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/bitcoincash/wallets/telr/ITelrCashProxyAPI.java, server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/bitcoincash/wallets/telr/TelrCashWallet.java, server_extensions_extra/src/main/resources/batm-extensions.xml
@pvyhnal-generalbytes thank you again for merging the Telr rate source. 
I'd like to move ahead now with the first of our wallets. The __Telr.io Cash Wallet__ has been running on a live BATM for a few weeks now. I'm confident everything should pass the @generalbytes review process.
FYI, this request ALSO has the completed authentication that was missing from the rate source.
=> Added Telr.io cash wallet to Bitcoin Cash extension.

server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/bitcoin/exchanges/XChangeExchange.java, server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/bitcoin/exchanges/binance/BinanceExchange.java, server_extensions_extra/src/test/java/com/generalbytes/batm/server/extensions/extra/bitcoin/exchanges/binance/BinanceExchangeRoundingTest.java, server_extensions_extra/src/test/java/com/generalbytes/batm/server/extensions/extra/bitcoin/exchanges/binance/BinanceExchangeTest.java
Round down the amount before trading to respect the minimum step for the currency pair
=> BATM-1191 BinanceExchange - Round down the amount before trading

server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/common/AbstractRPCPaymentSupport.java, server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/common/RPCClient.java
=> BATM-1204 support signrawtransactionwithwallet JSON RPC call

server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/bitcoin/exchanges/bitfinex/BitfinexExchange.java
remove after fixed in upstream
knowm/XChange/issues/3459
=> BATM-1219 hotfix bitfinex ratesource

server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/bitcoin/exchanges/binance/BinanceExchange.java, server_extensions_extra/src/test/java/com/generalbytes/batm/server/extensions/extra/ExchangeTest.java, server_extensions_extra/src/test/resources/logback-test.xml
This is just until it's fixed in upstream.
PR submitted to Xchange
https://github.com/knowm/XChange/pull/3500
=> BATM-1241 binance withdrawal workaround

.github/workflows/gradle.yml
this will run gradle build on every PR and show a warning before merging it if build fails. Tested on my fork:
=> Gradle GitHub Workflow

server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/bitcoin/BitcoinExtension.java, server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/bitcoin/exchanges/bitpandapro/BitpandaProExchange.java, server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/bitcoin/exchanges/bitpandapro/IBitpandaProAPI.java, server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/bitcoin/exchanges/bitpandapro/dto/Account.java, server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/bitcoin/exchanges/bitpandapro/dto/Balance.java, server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/bitcoin/exchanges/bitpandapro/dto/CreateDepositAddress.java, server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/bitcoin/exchanges/bitpandapro/dto/CreateOrder.java, server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/bitcoin/exchanges/bitpandapro/dto/CryptoWithdraw.java, server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/bitcoin/exchanges/bitpandapro/dto/DepositAddress.java, server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/bitcoin/exchanges/bitpandapro/dto/MarketTick.java, server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/bitcoin/exchanges/bitpandapro/dto/Order.java, server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/bitcoin/exchanges/bitpandapro/dto/OrderBookEntry.java, server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/bitcoin/exchanges/bitpandapro/dto/OrderBookSnapshot.java, server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/bitcoin/exchanges/bitpandapro/dto/OrderState.java, server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/bitcoin/exchanges/bitpandapro/dto/Side.java, server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/bitcoin/exchanges/bitpandapro/dto/WithdrawCrypto.java, server_extensions_extra/src/main/resources/batm-extensions.xml, server_extensions_extra/src/test/java/com/generalbytes/batm/server/extensions/extra/bitcoin/exchanges/bitpandapro/BitpandaProExchangeTest.java, server_extensions_extra/src/test/java/com/generalbytes/batm/server/extensions/extra/bitcoin/exchanges/bitpandapro/BitpandaProRateSourceTest.java
Hi!
I'm working on integrating [Bitpanda Pro](https://exchange.bitpanda.com/) as an exchange and rate source. Unfortunately Bitpanda Pro is not yet supported in XChange, therefore I'm implementing `IExchangeAdvanced` and `IRateSourceAdvanced` based on existing extensions.
~~This PR is work in progress currently:~~
=> Add exchange Bitpanda Pro

server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/dogecoin/DogecoinExtension.java, server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/dogecoin/wallets/blockio/BlockIOWalletWithClientSideSigning.java, server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/dogecoin/wallets/blockio/BlockIOWalletWithClientSideSigningWithUniqueAddresses.java, server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/dogecoin/wallets/blockio/IBlockIO.java, server_extensions_extra/src/main/resources/batm-extensions.xml
new "fromLabel" parameter for the block.io wallet (used only for withdrawals) to identify the address used to send the coins from
=> BPUB-1303 block.io optionally configurable label to withdraw from

server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/dogecoin/wallets/blockio/BlockIOWalletWithClientSideSigning.java, server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/dogecoin/wallets/blockio/IBlockIO.java
it was used for sending but not for getBalance and getCryptoAddress
=> BPUB-1303 fix "from label" block.io wallet parameter

server_extensions_extra/src/main/resources/batm-extensions.xml
…remove obsolete BitcoinClassic
=> BPUB-1380 change "bitcoincashd" wallet label (name) to include BCHN

server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/ethereum/InfuraWallet.java
report transaction as successful anyway - coins are being sent but it takes longer than 10s
reverts fb522a84ecbe96b74ddeaf238e9c3e663c5d6a93
=> BPUB-1394 ignore InfuraWallet timeout

server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/bitcoin/wallets/coinbase/v2/CBDigest.java, server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/bitcoin/wallets/coinbase/v2/CoinbaseWalletV2.java, server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/bitcoin/wallets/coinbase/v2/ICoinbaseV2API.java, server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/bitcoin/wallets/coinbase/v2/dto/CBWarning.java
#432 fixed this for coinbase exchange which is unfortunately implemented in a separate class
=> BPUB-1388 coinbase wallet accounts pagination

server_extensions_extra/src/main/resources/ilc.svg
Due to the logo issue at ATM screens, and because of new logo for ILCoin, we updated our SVG file for ILCoin.
If anything is wrong please let me now.
Best regards
=> new ILCoin logo

server_extensions_extra/src/main/resources/batm-extensions.xml
BCH sell works with bitcoind node/wallet only
=> CryptX - allow BCH only for buy

server_extensions_api/src/main/java/com/generalbytes/batm/server/extensions/IIdentity.java, server_extensions_api/src/main/java/com/generalbytes/batm/server/extensions/IOrganization.java
Introduced new interface IOrganization and added to IIdentity.
=> LC-21 Add IOrganization to IIdentity

server_extensions_extra/src/main/resources/batm-extensions.xml
+ rename legacy binance rate source
=> BATM-1752 Add ETH etc to Binance ratesource

server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/bitcoin/exchanges/bitpandapro/BitpandaProExchange.java, server_extensions_extra/src/test/java/com/generalbytes/batm/server/extensions/extra/bitcoin/exchanges/bitpandapro/BitpandaProRateSourceTest.java
Bitpanda Pro launched a DOGE/EUR market recently.
https://exchange.bitpanda.com/DOGE_EUR
=> [BitpandaPro] Add DOGE/EUR market

gradle.properties, server_extensions_api/src/main/java/com/generalbytes/batm/server/extensions/aml/scoring/ITransactionScoringProvider.java, server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/cardano/CardanoExtension.java, server_extensions_extra/src/main/resources/batm-extensions.xml
=> BATM-2229 add user ID to scoreCryptoAddress for Chainalysis support

gradle.properties, server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/bitcoin/exchanges/bittrex/BittrexAccountServiceCustom.java, server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/bitcoin/exchanges/bittrex/BittrexAuthenticatedCustom.java, server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/bitcoin/exchanges/bittrex/BittrexExchange.java, server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/bitcoin/exchanges/bittrex/BittrexExchangeCustom.java, server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/bitcoin/exchanges/bittrex/dto/BittrexNewWithdrawal.java, server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/bitcoin/exchanges/bittrex/dto/BittrexWithdrawal.java
Missing implementation of BittrexAccountService#withdrawFunds in org.knowm.xchange:xchange-bitfinex library
=> BATM-2323 Temporary fix for unimplemented BittrexAccountService#withdrawFunds 

server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/bitcoin/BitcoinExtension.java, server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/bitcoin/exchanges/coinzix/AskComparator.java, server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/bitcoin/exchanges/coinzix/BidComparator.java, server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/bitcoin/exchanges/coinzix/CoinZixExchange.java, server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/bitcoin/exchanges/coinzix/Constants.java, server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/bitcoin/exchanges/coinzix/RequestService.java, server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/bitcoin/exchanges/coinzix/dto/entities/Balance.java, server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/bitcoin/exchanges/coinzix/dto/entities/BalanceData.java, server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/bitcoin/exchanges/coinzix/dto/entities/Currency.java, server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/bitcoin/exchanges/coinzix/dto/entities/DepositAddress.java, server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/bitcoin/exchanges/coinzix/dto/entities/NewOrderId.java, server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/bitcoin/exchanges/coinzix/dto/entities/Order.java, server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/bitcoin/exchanges/coinzix/dto/entities/OrderBookData.java, server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/bitcoin/exchanges/coinzix/dto/entities/OrderBookPrice.java, server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/bitcoin/exchanges/coinzix/dto/entities/Ticker.java, server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/bitcoin/exchanges/coinzix/dto/entities/Withdraw.java, server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/bitcoin/exchanges/coinzix/dto/requests/BasicRequest.java, server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/bitcoin/exchanges/coinzix/dto/requests/GetDepositAddressRequest.java, server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/bitcoin/exchanges/coinzix/dto/requests/GetOrderRequest.java, server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/bitcoin/exchanges/coinzix/dto/requests/NewOrderRequest.java, server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/bitcoin/exchanges/coinzix/dto/requests/WithdrawRequest.java, server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/bitcoin/exchanges/coinzix/dto/responses/BalancesResponse.java, server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/bitcoin/exchanges/coinzix/dto/responses/BasicResponse.java, server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/bitcoin/exchanges/coinzix/dto/responses/GetDepositAddressResponse.java, server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/bitcoin/exchanges/coinzix/dto/responses/GetOrderResponse.java, server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/bitcoin/exchanges/coinzix/dto/responses/NewOrderResponse.java, server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/bitcoin/exchanges/coinzix/dto/responses/OrderBookResponse.java, server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/bitcoin/exchanges/coinzix/dto/responses/TickerResponse.java, server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/bitcoin/exchanges/coinzix/dto/responses/WithdrawResponse.java, server_extensions_extra/src/main/resources/batm-extensions.xml
Coinzix exchange integration for generalbytes dashboard
=> coinzix integration

server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/examples/activeTerminals/ActiveTerminalsExtension.java, server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/examples/activeTerminals/RestServiceActiveTerminals.java, server_extensions_extra/src/main/resources/batm-extensions.xml
RestService returns list of terminals with last ping < 5 min
=> Feature/batm 2509/rest service

server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/ethereum/erc20/DummyContractGasProvider.java, server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/ethereum/erc20/ERC20ContractGasProvider.java, server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/ethereum/erc20/ERC20Wallet.java
ContractGasProvider was using fixed amount of 1 token to estimate gas. Now a new ContractGasProvider will be constructed before every transaction with a correct token amount used
=> BPUB-1681 ERC20 gas estimate fix

server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/bitcoin/exchanges/XChangeExchange.java, server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/bitcoin/exchanges/binance/BinanceExchange.java
the result of amount.setScale wasn't used
=> BATM-2490 binance xrp withdrawal fix

gradle.properties, server_extensions_api/src/main/java/com/generalbytes/batm/server/extensions/watchlist/WatchListMatch.java, server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/watchlists/AbstractWatchList.java
* added WatchListMatch.partyId
* fixing indentation
* refactored according to CF-198
=> CF-197: Compliance 1 - Watchlist Scan Log

gradle.properties, server_extensions_api/src/main/java/com/generalbytes/batm/server/extensions/payment/PaymentRequest.java, server_extensions_api/src/test/java/com/generalbytes/batm/server/extensions/payment/PaymentRequestTest.java, server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/common/AbstractRPCPaymentSupport.java
MinimumNetworkFee was subtracted from the amount instead of the actually used network (mining) fee
=> BATM-2669 correct amount to be sold on exchange

server_extensions_api/src/main/java/com/generalbytes/batm/server/extensions/Country.java
=> BATM-3074 add Kosovo to the list of countries

dependencyChecksums.txt, gradle.properties, server_extensions_extra/build.gradle, server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/bitcoin/exchanges/XChangeExchange.java, server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/bitcoin/exchanges/ftx/FtxComExchange.java, server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/bitcoin/exchanges/ftx/FtxExchange.java, server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/bitcoin/exchanges/ftx/FtxUsExchange.java, server_extensions_extra/src/main/resources/batm-extensions.xml, server_extensions_extra/src/test/java/com/generalbytes/batm/server/extensions/extra/ExchangeTest.java, server_extensions_extra/src/test/java/com/generalbytes/batm/server/extensions/extra/RateSourceTest.java
For now the exchange integration (xchange library) does not support deposit and withdraw. Only purchase / sell and rate source is supported
=> BPUB-1769 FTX exchange support

dependencyChecksums.txt, server_extensions_extra/build.gradle
this is just to have the same version in public and batm_server
=> CF-481 update zxing library

server_extensions_api/src/main/java/com/generalbytes/batm/server/extensions/watchlist/WatchListResult.java, server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/watchlists/AbstractWatchList.java, server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/watchlists/czech/CzechSanctionList.java
the change in main does not depend on this
=> CF-542 watchlists refactor

server_extensions_extra/src/main/resources/batm-extensions.xml
=> - Allow sell transactions for ETH & USDT on CryptX wallet

server_extensions_api/src/main/java/com/generalbytes/batm/server/extensions/ITransactionListener.java, server_extensions_template/build.gradle, server_extensions_template/src/main/java/com/mygreatcompany/batm/server/extensions/myfirstextension/MyFirstExtension.java, server_extensions_template/src/main/java/com/mygreatcompany/batm/server/extensions/myfirstextension/MyTransactionListener.java, server_extensions_template/src/main/resources/batm-extensions.xml, settings.gradle
Extension template should make it easier for operators to start writing their extensions and not to extend the "extras" extension.
=> BATM-5644 -   Create template module for customers to develop their extensions

server_extensions_api/src/main/java/com/generalbytes/batm/server/extensions/Converters.java, server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/bitcoin/wallets/cryptx/v2/CryptXWallet.java, server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/bitcoin/wallets/cryptx/v2/CryptXWithUniqueAddresses.java, server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/bitcoin/wallets/cryptx/v2/ICryptXAPI.java, server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/bitcoin/wallets/cryptx/v2/dto/CryptXReceivedAmount.java, server_extensions_extra/src/main/resources/batm-extensions.xml
Add TRON Network support for CryptX wallet
=> Update CryptX wallet to process USDT in TRON network

batm_ssh_tunnel/build.gradle, server_extensions_examples/build.gradle, server_extensions_template/build.gradle, settings.gradle
Cherry-pick of 1f7bc9c5b8837c93c0929d5c1e9f720a3c1498e0
=> Remove duplicate repo settings from build.gradle files (#903)

server_extensions_api/src/main/java/com/generalbytes/batm/server/extensions/ICustomString.java, server_extensions_api/src/main/java/com/generalbytes/batm/server/extensions/IExtensionContext.java, server_extensions_api/src/main/java/com/generalbytes/batm/server/extensions/ITransactionDetails.java
=> CF-672: added properties to transaction detail and changed method returning custom string data

annotations/build.gradle, batm_ssh_tunnel/build.gradle, build.gradle, buildSrc/src/main/groovy/shared-build-conventions.gradle, currencies/build.gradle, operators_sample_website/build.gradle, server_extensions_api/build.gradle, server_extensions_examples/build.gradle, server_extensions_extra/build.gradle, server_extensions_template/build.gradle, server_extensions_test/build.gradle
Cherry-pick of `f09800ac76426014060ca49d378b2b934ab71f8b`
=> BATM-6544 Fix where convention plugins are applied (#924)

server_extensions_api/src/main/java/com/generalbytes/batm/server/extensions/travelrule/ITravelRuleProvider.java
=> BATM-7269: add ITravelRuleProvider#verifyCustomerDeclaredCustodialWallet method

server_extensions_api/src/main/java/com/generalbytes/batm/server/extensions/travelrule/IIdentityWalletEvaluationRequest.java, server_extensions_api/src/main/java/com/generalbytes/batm/server/extensions/travelrule/ITravelRuleTransferData.java, server_extensions_extra/src/test/java/com/generalbytes/batm/server/extensions/travelrule/notabene/NotabeneTravelRuleProviderTest.java
added beneficiary VASP to IIdentityWalletEvaluationRequest + added javadoc to crypto address
=> BATM-7269: add host VASP ID to IIdentityWalletEvaluationRequest

server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/bitcoin/wallets/cryptx/v2/CryptXWallet.java, server_extensions_extra/src/main/resources/batm-extensions.xml
added usdc support for CryptxWallet clients
=> Added USDC support for CryptxWallet

server_extensions_api/src/main/java/com/generalbytes/batm/server/extensions/ITerminal.java
(cherry picked from commit 3f3686dcf4ad58d8b0765304b234e37ab0ffe8ae)
=> CF-886: Add organization ID to ITerminal (#1064)
